DROP TABLE COURSE_ENROLLMENT;
CREATE TABLE COURSE_ENROLLMENT ( ENROLLMENT_ID NUMBER PRIMARY KEY , USER_ID NUMBER, COURSE_ID VARCHAR2(100) , FEES NUMBER DEFAULT 0 );

CREATE TABLE COURSE_FEES ( COURSE_ID VARCHAR2(100) , FEES NUMBER , UNIQUE (COURSE_ID ) );
insert into COURSE_FEES ( COURSE_ID, FEES) 
VALUES ( 'C', 1000);

insert into COURSE_FEES ( COURSE_ID, FEES) 
VALUES ( 'SQL', 5000);


insert into COURSE_ENROLLMENT ( USER_ID, COURSE_ID) VALUES (1,'C');


CREATE OR REPLACE TRIGGER TR_COURSE_FEE 
AFTER INSERT ON COURSE_ENROLLMENT FOR EACH ROW
DECLARE
V_FEES NUMBER;
BEGIN
  SELECT FEES INTO V_FEES FROM COURSE_FEES WHERE COURSE_ID = :new.COURSE_ID;
  UPDATE COURSE_ENROLLMENT SET FEES = V_FEES WHERE ENROLLMENT_ID = :new.ENROLLMENT_ID;
  COMMIT;
END;
